apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskboard-root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/apurvdugar/devops-heros.git
    targetRevision: main
    path: session21-python/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
