replicaCount: 1
frontend:
  image: taskboard-frontend
  tag: local
backend:
  image: taskboard-backend
  tag: local
ingress:
  enabled: true
  host: taskboard.local
hpa:
  enabled: false
monitoring:
  serviceMonitor:
    enabled: false
